### ISSUE TITLE
How to pass first name and last name along with email in subscribe post method

### ISSUE THREAD

**Issue by gman6995** [zf-fr/zfr-mailchimp#30]
$client->subscribe(array(
                'id' => env("MAILCHIMP_LIST_ID"),
                'email' => array(
                    'email' => $request->email
                )
            ));

**Comment by bakura10** [comment]
Hi,

Unfortunately, this library supports an outdated version of the API, the v2, as stated in the info here: https://github.com/zf-fr/zfr-mailchimp

I will likely deprecate this library, in the meantime I'd recommend you to use another PHP library that supports the v3.
